plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

version = project.citadel_version
group = 'com.github.alexthe666.citadel'
base {
    archivesName = "citadelfabric"
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        name = 'Fabric'
        url = 'https://maven.fabricmc.net/'
    }
}

sourceSets {
    main {
        java {
            srcDirs = ['main/java', 'client/java']
        }
        resources {
            srcDirs = ['main/resources', 'client/resources']
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": inputs.properties.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
    it.options.compilerArgs += ['-Xmaxerrs', '100000']
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    from("LICENSE")
    from("README.md")
}

tasks.matching { it.name in ['runClient', 'runServer'] }.configureEach {
    enabled = false
}
